# IDC Dataset Configuration
# Imaging Data Commons CT dataset

_imports_:
    monai: monai

vars:
    idc_dataset: "/mnt/ssd1/ibro/IDC_SSL_CT"

data:
    train_dataset:
        dataset:
            data: "$monai.auto3dseg.datafold_read(@vars::idc_dataset + '/idc_dump_datalist.json', basedir='', key='training')[0]"
